package de.turnflow.session.entity;

public enum TrainingSessionActionDisabledReason {
    MEMBER_INACTIVE,
    NOT_ALLOWED_FOR_GROUP,
    SESSION_NOT_OPEN,
    SESSION_IN_PAST,
    REGISTRATION_DEADLINE_EXPIRED,
    SESSION_FULL,
    ALREADY_REGISTERED,
    ALREADY_WAITLISTED,
    NOT_REGISTERED,
    ALREADY_CANCELLED,
    UNREGISTER_AFTER_SESSION_END_NOT_ALLOWED
}